platform :ios, '13.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'dreiAttestTests' do
    pod 'Alamofire', '~> 5.4.0'
    pod 'Mocker', '~> 2.2.0'
    pod 'SwiftCBOR', '~> 0.4.3'
    pod 'DogSwift', '~> 1.1.1'
end
